# Generated by Django 2.0.6 on 2020-09-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=50, null=True)),
                ('book_author', models.CharField(blank=True, max_length=50, null=True)),
                ('book_pulish', models.CharField(blank=True, max_length=50, null=True)),
                ('pulish_time', models.DateField(blank=True, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('book_isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('open_type', models.CharField(blank=True, max_length=20, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('book_wrapper', models.CharField(blank=True, max_length=20, null=True)),
                ('book_paper', models.CharField(blank=True, max_length=20, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('editor_recommendatio', models.IntegerField(blank=True, null=True)),
                ('content_introduction', models.CharField(blank=True, max_length=20, null=True)),
                ('product_image_path', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_class',
            },
        ),
        migrations.AddField(
            model_name='tbook',
            name='class_field',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.TClass'),
        ),
    ]
